[package]
name = "huffman-coding-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = { version = "1", features = ["serde"] }
clap = { version = "4.5.49", features = ["derive"] }
rmp-serde = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }

